<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function blog_prev_next_theme($existing, $type, $theme, $path)
{
    return [
        'blog_prev_next' => [
            'variables' => [
                'entity' => NULL,
            ],
            'file' => 'blog_prev_next.theme.inc',
        ],
    ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function blog_prev_next_entity_extra_field_info()
{
    $extra = [];

    foreach (NodeType::loadMultiple() as $bundle) {
        $extra['node'][$bundle->id()]['display']['previous_next'] = [
            'label' => t('Buttons to previous and next entity'),
            'weight' => 100,
            'visible' => FALSE,
        ];
    }

    return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function blog_prev_next_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
    if ($display->getComponent('previous_next')) {
        $build['previous_next'] = [
            '#theme' => 'blog_prev_next',
            '#entity' => $node,
        ];
    }
}